apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: deploysampleappstack.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: DeploySampleAppStack
    spec:
      name: string
  resources:
  - id: tektonpipeline
    template:
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: pipeline-segoja7
        namespace: tekton-pipelines
      spec:
        params:
        - name: cluster-name
          type: string
        - name: aws-region
          type: string
        - name: game-yaml-url
          type: string
        workspaces:
        - name: aws-credentials
        tasks:
        - name: authenticate-eks-segoja7
          taskRef:
            name: authenticate-eks-segoja7
          params:
          - name: cluster-name
            value: $(params.cluster-name)
          - name: aws-region
            value: $(params.aws-region)
          workspaces:
          - name: aws-credentials
            workspace: aws-credentials
        - name: deploy-app-segoja7
          taskRef:
            name: deploy-app-segoja7
          params:
          - name: game-yaml-url
            value: $(params.game-yaml-url)
          workspaces:
          - name: aws-credentials
            workspace: aws-credentials
